### PR TITLE
DAC6-910: Migrate to Play 2.8

### PR DESCRIPTION
**Pull request by cameronstalker1**

### CODE REVIEW

**Review by soljeggers — COMMENTED** [review]
May be cleaner to update mode model to write out JsString instead of manually changing each spec?
```

  implicit val checkWrites: Writes[CheckMode.type] =  Writes { _ =&gt; JsString("CheckMode")}  
  implicit val normalWrites: Writes[NormalMode.type] = Writes { _ =&gt; JsString("NormalMode")}
```

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Comment by hmrc-web-operations** [comment]
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/master/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

**Review by soljeggers — APPROVED** [review]

**Pull request merged**
